version: "3.9"

services:
  sample-app-client:
    image: yarche/sample-tracing-app:${TAG:-v1.0.0}
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - LISTEN_PORT=3000
      - SERVER_PORT=8080
      - SERVER_HOST=sample-app-server
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=Monitoring,service.name=SampleTracingApp
      - SECRET=secret_token
    ports:
      - "3000:3000"
    command: ["node", "client.js"]

  sample-app-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - PORT=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=Monitoring,service.name=SampleTracingApp
      - AWS_REGION=eu-west-1
      - SECRET=secret_token
    ports:
      - "8080:8080"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.40.0
    command: ["--config=/etc/ecs/otel-instance-metrics-config.yaml"]
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - ./infrastructure/opentelemetry/local/otel-instance-metrics-config.yaml:/etc/ecs/otel-instance-metrics-config.yaml
    ports:
      - "13133"       # health_check
      - "4317:4317"   # OTel Collector exporter EP gRPC default port
      - "4318:4318"   # OTel Collector exporter EP http default port (/v1/metrics, /v1/traces, /v1/logs)
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
      - zipkin

  # @goto http://localhost:9411/zipkin for UI
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "14268"       # http trace push EP
      - "16685"
